---
- name: Full system upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Ensure unattended_upgrades, debconf are present
  ansible.builtin.package:
    name:
      - debconf
      - debconf-utils
      - unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: 'true'
  notify: dpkg-reconfigure unattended-upgrades

- name: 'Enable timer {{ item }}'
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
